# This is a basic workflow to help you get started with Actions

name: Code Formatter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # Runs autoflake
      - name: autoflake
        run: |
          pip install autoflake
          autoflake -r --in-place --remove-all-unused-imports .
      
      # Runs black
      - name: black
        run: |
          pip install black
          black .

      # Runs isort
      - name: isort
        run: |
          pip install isort
          isort .
        
      # Commit changes
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git diff
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git diff-index --quiet HEAD || git commit -am "Automated reformatting"
          git push
